import { LoaderCircle, Play, Rows3 } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { EmptyState } from "../components/common/EmptyState";
import { PageHeader } from "../components/layout/PageHeader";
import { useWorkflow } from "../features/files/WorkflowContext";
import { previewRows } from "../services/fileApi";
import { runValidation } from "../services/validationApi";

export function PreviewRowsPage(){const nav=useNavigate();const {files,templates,rows,setRows,mode,projectName,setResult}=useWorkflow();const [busy,setBusy]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{let active=true;(async()=>{try{for(const file of files){const template=templates[file.id];if(!template)throw new Error(`Mapping missing for ${file.name}.`);const response=await previewRows(file.id,template);if(active)setRows(file.id,response.rows)}}catch(e){if(active)setError(e instanceof Error?e.message:"Preview failed.")}finally{if(active)setBusy(false)}})();return()=>{active=false}},[files,templates]);
  const validate=async()=>{setBusy(true);setError("");try{const byRole=(role:string)=>files.find(f=>templates[f.id]?.file_role===role);const ref=byRole("reference")??files[0], bidder=byRole("bidder"), abs=byRole("abstract");const comparison=mode==="reference_bidder_abstract"?abs:(files.find(f=>f.id!==ref?.id));const result=await runValidation({project_name:projectName,mode,reference_rows:ref?rows[ref.id]??[]:[],comparison_rows:comparison?rows[comparison.id]??[]:[],bidder_rows:bidder?rows[bidder.id]??[]:[],abstract_rows:abs?rows[abs.id]??[]:[],compare_fields:mode==="reference_vs_copied"?["description","quantity"]:["description","quantity","unit","unit_cost","total_cost"],case_insensitive:true});setResult(result);nav("/results")}catch(e){setError(e instanceof Error?e.message:"Validation failed.")}finally{setBusy(false)}};
  if(!files.length)return <div><PageHeader eyebrow="Step 3 of 5" title="Confirm extracted rows" description="Upload and map files first."/><div className="pt-8"><EmptyState icon={Rows3} title="Nothing to preview" description="Complete file mapping before extraction."/></div></div>;
  return <div><PageHeader eyebrow="Step 3 of 5" title="Confirm extracted rows" description="Check the source sheet, Excel row, description, quantity, and prices before running validation."/><div className="space-y-6 pt-8">{busy&&<p className="flex items-center gap-2 text-sm text-slate-600"><LoaderCircle className="size-4 animate-spin"/>Processing local rows…</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{files.map(file=><section key={file.id}><div className="mb-3 flex items-end justify-between"><div><h2 className="font-semibold">{file.name}</h2><p className="text-xs text-slate-500">{rows[file.id]?.length??0} valid rows extracted</p></div></div><div className="max-h-72 overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-100 text-xs text-slate-600"><tr><th className="p-3">Sheet / row</th><th className="p-3">Item</th><th className="p-3">Description</th><th className="p-3">Quantity</th><th className="p-3">Unit cost</th><th className="p-3">Total</th></tr></thead><tbody>{(rows[file.id]??[]).slice(0,100).map(row=><tr key={`${row.sheet_name}-${row.excel_row_number}`} className="border-t border-slate-100"><td className="whitespace-nowrap p-3 text-xs text-slate-500">{row.sheet_name} · {row.excel_row_number}</td><td className="p-3">{row.item_number??"—"}</td><td className="max-w-md p-3">{row.item_description}</td><td className="p-3">{row.quantity??"—"}</td><td className="p-3">{row.unit_cost??"—"}</td><td className="p-3">{row.total_cost??"—"}</td></tr>)}</tbody></table></div></section>)}<button disabled={busy||Object.keys(rows).length<files.length} onClick={validate} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Play className="size-4"/>Run validation</button></div></div>}
