import { FileSpreadsheet, FileUp, LoaderCircle, LockKeyhole, X } from "lucide-react";
import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader } from "../components/layout/PageHeader";
import { FieldLabel, HelpTip, SelectField } from "../components/forms";
import { useWorkflow } from "../features/files/WorkflowContext";
import { uploadFiles } from "../services/fileApi";
import type { ComparisonMode } from "../types/validation.types";
import { isSupportedFileName } from "../utils/validators";

export function UploadFilesPage() {
  const navigate=useNavigate(); const input=useRef<HTMLInputElement>(null); const {projectName,setProjectName,mode,setMode,files,setFiles}=useWorkflow();
  const [selected,setSelected]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [dragActive,setDragActive]=useState(false);
  const add=(list:File[])=>{const valid=list.filter(f=>isSupportedFileName(f.name)); setError(valid.length!==list.length?"Only .xlsx, .xls, and .csv files are accepted.":""); setSelected(p=>[...p,...valid].slice(0,10));};
  const submit=async()=>{if(!selected.length)return; setBusy(true);setError("");try{setFiles(await uploadFiles(selected));navigate("/mapping");}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false)}};
  return <div><PageHeader eyebrow="Step 1 of 5" title="Choose comparison files" description="Select the project mode and local spreadsheets. Files are processed on this device and originals remain unchanged." />
    <div className="grid grid-cols-[320px_minmax(0,1fr)] gap-8 pt-8"><section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5">
      <div><div className="flex items-center gap-1"><label htmlFor="session-name" className="text-sm font-semibold text-slate-900">Session name</label><HelpTip text="Give this review a clear name, such as the project, purchase request, or bidding activity name. This name will appear in the PDF report." /></div><input id="session-name" value={projectName} onChange={e=>setProjectName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-emerald-600" /></div>
      <div><FieldLabel className="text-sm text-slate-900" help="Choose how the files are related. Use Reference vs copied file for a simple check, Reference + bidder + abstract for bid calculations, or Generic for two files with fields you choose.">Comparison mode</FieldLabel><SelectField className="mt-2" ariaLabel="Comparison mode" value={mode} onChange={(value)=>setMode(value as ComparisonMode)} options={[{value:"reference_vs_copied",label:"Reference vs copied file",description:"Compare descriptions and quantities from an original reference against a copied or newly prepared file."},{value:"reference_bidder_abstract",label:"Reference + bidder + abstract",description:"Use reference quantities and bidder unit prices to verify the abstract or newly copied file."},{value:"generic_two_file",label:"Generic two-file comparison",description:"Compare two files using the fields you map, without assigning procurement-specific source roles."}]} /></div>
      <div className="rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800"><LockKeyhole className="mb-2 size-4" />No cloud upload, account, or internet connection is used.</div>
    </section><section><div className="mb-2 flex items-center gap-1 text-sm font-semibold text-slate-700">Files to compare <HelpTip text="Choose the Excel or CSV files you want to compare. You can select up to 10 files. The application reads a temporary local copy and never changes the originals." /></div><button title="Choose local Excel or CSV files" type="button" onClick={()=>input.current?.click()} onDragEnter={e=>{e.preventDefault();setDragActive(true)}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="copy";setDragActive(true)}} onDragLeave={e=>{e.preventDefault();if(!e.currentTarget.contains(e.relatedTarget as Node))setDragActive(false)}} onDrop={e=>{e.preventDefault();setDragActive(false);add([...e.dataTransfer.files])}} className={`grid min-h-52 w-full place-items-center rounded-2xl border border-dashed p-8 text-center transition active:scale-[0.99] ${dragActive?"border-emerald-600 bg-emerald-50 ring-4 ring-emerald-100":"border-slate-300 bg-white hover:border-emerald-500 hover:bg-emerald-50/30"}`}><span><FileUp className={`mx-auto size-7 text-emerald-700 transition-transform ${dragActive?"-translate-y-1 scale-110":""}`}/><span className="mt-3 block font-semibold">{dragActive?"Release to add files":"Drop spreadsheets here or browse"}</span><span className="mt-1 block text-sm text-slate-500">Up to 10 files, 50 MB each</span></span></button><input ref={input} hidden multiple type="file" accept=".xlsx,.xls,.csv" onChange={e=>add([...(e.target.files??[])])}/>
      <div className="mt-4 space-y-2">{selected.map((file,i)=><div key={`${file.name}-${i}`} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><FileSpreadsheet className="size-5 text-emerald-700"/><span className="min-w-0 flex-1 truncate text-sm font-medium">{file.name}</span><span className="text-xs text-slate-500">{(file.size/1024).toFixed(0)} KB</span><button title={`Remove ${file.name} from this review`} onClick={()=>setSelected(p=>p.filter((_,index)=>index!==i))} aria-label={`Remove ${file.name}`}><X className="size-4"/></button></div>)}</div>
      {error&&<p className="mt-3 text-sm text-red-700" role="alert">{error}</p>}<button title="Read the selected files and continue to sheet and column setup" disabled={!selected.length||busy} onClick={submit} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy?<LoaderCircle className="size-4 animate-spin"/>:null}{busy?"Inspecting files…":"Continue to mapping"}</button>
      {files.length>0&&<p className="mt-3 text-xs text-slate-500">{files.length} previously inspected file(s) in this session.</p>}</section></div></div>;
}
