import { FileSearch, Search } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/common/EmptyState";
import { PageHeader } from "../components/layout/PageHeader";
import { SelectField } from "../components/forms";
import { useWorkflow } from "../features/files/WorkflowContext";

export function ValidationResultsPage(){const {result}=useWorkflow();const [query,setQuery]=useState("");const [severity,setSeverity]=useState("all");if(!result)return <div><PageHeader eyebrow="Step 4 of 5" title="Review discrepancies" description="Run validation to populate results."/><div className="pt-8"><EmptyState icon={FileSearch} title="No validation result" description="Confirm extracted rows and run validation first."/></div></div>;
  const filtered=result.discrepancies.filter(d=>(severity==="all"||d.severity===severity)&&`${d.reference_description??""} ${d.comparison_description??""} ${d.issue_type}`.toLowerCase().includes(query.toLowerCase()));
  return <div><PageHeader eyebrow="Step 4 of 5" title="Review discrepancies" description={`${result.discrepancies.length} issue(s) found across ${result.total_rows} extracted rows. Every issue retains its source location.`} action={<Link to="/reports" className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white">Export report</Link>}/><div className="grid grid-cols-4 divide-x divide-slate-200 border-b border-slate-200 py-6">{[["Total",result.discrepancies.length],["High",result.discrepancies.filter(d=>d.severity==="high").length],["Medium",result.discrepancies.filter(d=>d.severity==="medium").length],["Rows reviewed",result.total_rows]].map(([l,v])=><div key={String(l)} className="px-5 first:pl-0"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div><div className="flex gap-3 py-5"><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search descriptions or issue types" className="min-h-11 w-full rounded-xl border border-slate-300 bg-white py-2 pl-9 pr-3 text-sm outline-none transition focus:border-emerald-600 focus:ring-3 focus:ring-emerald-100"/></label><SelectField className="w-48" ariaLabel="Filter by severity" value={severity} onChange={setSeverity} options={[{value:"all",label:"All severities"},{value:"high",label:"High"},{value:"medium",label:"Medium"},{value:"low",label:"Low"}]} /></div><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-xs text-slate-600"><tr><th className="p-3">Severity</th><th className="p-3">Issue</th><th className="p-3">Location</th><th className="p-3">Reference</th><th className="p-3">Actual</th><th className="p-3">Suggested correction</th></tr></thead><tbody>{filtered.map((d,i)=><tr key={i} className="border-t border-slate-100 align-top"><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${d.severity==="high"?"bg-red-50 text-red-700":d.severity==="medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700"}`}>{d.severity}</span></td><td className="p-3 font-medium">{d.issue_type.replaceAll("_"," ")}</td><td className="whitespace-nowrap p-3 text-xs text-slate-600">{d.comparison_sheet??d.reference_sheet} · row {d.comparison_row??d.reference_row}</td><td className="max-w-xs p-3">{d.expected_value??d.reference_description??"—"}</td><td className="max-w-xs p-3">{d.actual_value??d.comparison_description??"—"}</td><td className="max-w-xs p-3 text-slate-600">{d.suggested_correction??d.notes??"Review item."}</td></tr>)}</tbody></table>{!filtered.length&&<p className="p-8 text-center text-sm text-slate-500">No discrepancies match the current filters.</p>}</div></div>}
